services:
  nearRT-RIC:
#    image: oaisoftwarealliance/oai-flexric:develop
    image: rah_flexric:latest
#    command: "stdbuf -o0 nearRT-RIC"
    container_name: nearRT-RIC
    stdin_open: true
    tty: true
    privileged: true
    expose:
      - "36421/sctp"
      - "36422/sctp"
#    ports:
#      - "36421:36421/sctp"
#      - "36422:36422/sctp"
    networks:
      e2-net:
#        ipv4_address: 172.32.1.1
        ipv4_address: ${NEAR_RT_RIC_E2_IP}
    volumes:
      - ./flexric/:/mnt/

#  xapp-kpm-moni:
#    image: rah_flexric:latest
##    command: "stdbuf -o0 /usr/local/flexric/xApp/c/monitor/xapp_kpm_moni"
#    command: "build/examples/xApp/c/monitor/xapp_oran_moni -c /mnt/xapp_mon_e2sm_kpm.conf"
#    container_name: xapp-kpm-moni
##    environment:
##      - XAPP_DURATION=20
#    depends_on:
#      - nearRT-RIC
#    networks:
#      e2-net:
#        ipv4_address: ${KPM_E2_IP}
#    volumes:
#      - ./flexric/:/mnt/
#
#  xapp-rc-moni:
#    image: oai-flexric:dev
#    command: "stdbuf -o0 /usr/local/flexric/xApp/c/monitor/xapp_rc_moni"
#    container_name: xapp-rc-moni
#    environment:
#      - XAPP_DURATION=20
#    depends_on:
#      - nearRT-RIC
#      - emu-gnb-mono
#      - emu-cu
#      - emu-du
#    networks:
#      e2_net:
#        ipv4_address: 192.168.72.156
#    volumes:
#      - ./flexric.conf:/usr/local/etc/flexric/flexric.conf
#
#  xapp-gtp-mac-rlc-pdcp-moni:
#    image: oai-flexric:dev
#    command: "stdbuf -o0 /usr/local/flexric/xApp/c/monitor/xapp_gtp_mac_rlc_pdcp_moni"
#    container_name: xapp-gtp-mac-rlc-pdcp-moni
#    environment:
#      - XAPP_DURATION=20
#    depends_on:
#      - nearRT-RIC
#      - emu-gnb-mono
#      - emu-cu
#      - emu-du
#    networks:
#      e2_net:
#        ipv4_address: 192.168.72.157
#    volumes:
#      - ./flexric.conf:/usr/local/etc/flexric/flexric.conf

networks:
  e2-net:
    name: e2-net
    ipam:
      config:
#        - subnet: 172.32.1.0/24
        - subnet: ${E2_NETWORK}
    driver_opts:
      com.docker.network.bridge.name: "do5g_e2_br"